// Code generated by pigeon; DO NOT EDIT.

package filter

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

type ComparisonNode struct {
	Type     string
	Operator CodeNode
	Values   interface{}
}

type CodeNode struct {
	Type          string
	Source        string
	Value         string
	JsonbSelector []CodeNode
}

type FunctionNode struct {
	Name     string
	Function CodeNode
	Args     []CodeNode
}

func toIfaceSlice(v interface{}) []interface{} {
	if v == nil {
		return nil
	}
	return v.([]interface{})
}

func eval(first, rest interface{}) []interface{} {
	exprs := []interface{}{}
	exprs = append(exprs, first)
	restSl := toIfaceSlice(rest)
	for _, v := range restSl {
		restStmt := toIfaceSlice(v)
		exprs = append(exprs, restStmt[3])
	}
	return exprs
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 50, col: 1, offset: 785},
			expr: &actionExpr{
				pos: position{line: 50, col: 10, offset: 794},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 50, col: 10, offset: 794},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 50, col: 10, offset: 794},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 50, col: 12, offset: 796},
							label: "i",
							expr: &ruleRefExpr{
								pos:  position{line: 50, col: 14, offset: 798},
								name: "OrComparison",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 50, col: 27, offset: 811},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 50, col: 29, offset: 813},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "OrComparison",
			pos:  position{line: 54, col: 1, offset: 838},
			expr: &actionExpr{
				pos: position{line: 54, col: 17, offset: 854},
				run: (*parser).callonOrComparison1,
				expr: &seqExpr{
					pos: position{line: 54, col: 17, offset: 854},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 54, col: 17, offset: 854},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 54, col: 23, offset: 860},
								name: "AndComparison",
							},
						},
						&labeledExpr{
							pos:   position{line: 54, col: 37, offset: 874},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 54, col: 42, offset: 879},
								expr: &seqExpr{
									pos: position{line: 54, col: 44, offset: 881},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 54, col: 44, offset: 881},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 54, col: 46, offset: 883},
											name: "Or",
										},
										&ruleRefExpr{
											pos:  position{line: 54, col: 49, offset: 886},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 54, col: 51, offset: 888},
											name: "AndComparison",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AndComparison",
			pos:  position{line: 66, col: 1, offset: 1066},
			expr: &actionExpr{
				pos: position{line: 66, col: 18, offset: 1083},
				run: (*parser).callonAndComparison1,
				expr: &seqExpr{
					pos: position{line: 66, col: 18, offset: 1083},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 66, col: 18, offset: 1083},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 66, col: 24, offset: 1089},
								name: "Comparison",
							},
						},
						&labeledExpr{
							pos:   position{line: 66, col: 35, offset: 1100},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 66, col: 40, offset: 1105},
								expr: &seqExpr{
									pos: position{line: 66, col: 42, offset: 1107},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 66, col: 42, offset: 1107},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 66, col: 44, offset: 1109},
											name: "And",
										},
										&ruleRefExpr{
											pos:  position{line: 66, col: 48, offset: 1113},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 66, col: 50, offset: 1115},
											name: "Comparison",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Comparison",
			pos:  position{line: 83, col: 1, offset: 1314},
			expr: &choiceExpr{
				pos: position{line: 83, col: 16, offset: 1329},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 83, col: 16, offset: 1329},
						name: "MultiComparison",
					},
					&ruleRefExpr{
						pos:  position{line: 83, col: 34, offset: 1347},
						name: "NotComparison",
					},
					&ruleRefExpr{
						pos:  position{line: 83, col: 50, offset: 1363},
						name: "LeftRightComparison",
					},
					&ruleRefExpr{
						pos:  position{line: 83, col: 72, offset: 1385},
						name: "LikeComparison",
					},
					&ruleRefExpr{
						pos:  position{line: 83, col: 89, offset: 1402},
						name: "IsComparison",
					},
					&ruleRefExpr{
						pos:  position{line: 83, col: 104, offset: 1417},
						name: "InComparison",
					},
					&ruleRefExpr{
						pos:  position{line: 83, col: 119, offset: 1432},
						name: "IdentifierComparison",
					},
				},
			},
		},
		{
			name: "MultiComparison",
			pos:  position{line: 85, col: 1, offset: 1454},
			expr: &actionExpr{
				pos: position{line: 85, col: 20, offset: 1473},
				run: (*parser).callonMultiComparison1,
				expr: &seqExpr{
					pos: position{line: 85, col: 20, offset: 1473},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 85, col: 20, offset: 1473},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 85, col: 24, offset: 1477},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 85, col: 26, offset: 1479},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 85, col: 31, offset: 1484},
								name: "OrComparison",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 85, col: 44, offset: 1497},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 85, col: 46, offset: 1499},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "NotComparison",
			pos:  position{line: 89, col: 1, offset: 1527},
			expr: &actionExpr{
				pos: position{line: 89, col: 18, offset: 1544},
				run: (*parser).callonNotComparison1,
				expr: &seqExpr{
					pos: position{line: 89, col: 18, offset: 1544},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 89, col: 18, offset: 1544},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 89, col: 21, offset: 1547},
								name: "Not",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 89, col: 25, offset: 1551},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 89, col: 27, offset: 1553},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 89, col: 33, offset: 1559},
								name: "Comparison",
							},
						},
					},
				},
			},
		},
		{
			name: "LeftRightComparison",
			pos:  position{line: 98, col: 1, offset: 1718},
			expr: &actionExpr{
				pos: position{line: 98, col: 24, offset: 1741},
				run: (*parser).callonLeftRightComparison1,
				expr: &seqExpr{
					pos: position{line: 98, col: 24, offset: 1741},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 98, col: 24, offset: 1741},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 98, col: 29, offset: 1746},
								name: "Value",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 98, col: 35, offset: 1752},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 98, col: 37, offset: 1754},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 98, col: 40, offset: 1757},
								name: "CompareOperator",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 98, col: 56, offset: 1773},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 98, col: 58, offset: 1775},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 98, col: 64, offset: 1781},
								name: "Value",
							},
						},
					},
				},
			},
		},
		{
			name: "LikeComparison",
			pos:  position{line: 107, col: 1, offset: 1944},
			expr: &actionExpr{
				pos: position{line: 107, col: 19, offset: 1962},
				run: (*parser).callonLikeComparison1,
				expr: &seqExpr{
					pos: position{line: 107, col: 19, offset: 1962},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 107, col: 19, offset: 1962},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 107, col: 25, offset: 1968},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 107, col: 37, offset: 1980},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 107, col: 39, offset: 1982},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 107, col: 42, offset: 1985},
								name: "Like",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 107, col: 47, offset: 1990},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 107, col: 49, offset: 1992},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 107, col: 56, offset: 1999},
								name: "String",
							},
						},
					},
				},
			},
		},
		{
			name: "IsComparison",
			pos:  position{line: 116, col: 1, offset: 2161},
			expr: &actionExpr{
				pos: position{line: 116, col: 17, offset: 2177},
				run: (*parser).callonIsComparison1,
				expr: &seqExpr{
					pos: position{line: 116, col: 17, offset: 2177},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 116, col: 17, offset: 2177},
							label: "left",
							expr: &choiceExpr{
								pos: position{line: 116, col: 23, offset: 2183},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 116, col: 23, offset: 2183},
										name: "Identifier",
									},
									&ruleRefExpr{
										pos:  position{line: 116, col: 36, offset: 2196},
										name: "Null",
									},
									&ruleRefExpr{
										pos:  position{line: 116, col: 43, offset: 2203},
										name: "Bool",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 116, col: 49, offset: 2209},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 116, col: 51, offset: 2211},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 116, col: 54, offset: 2214},
								name: "Is",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 116, col: 57, offset: 2217},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 116, col: 59, offset: 2219},
							label: "right",
							expr: &choiceExpr{
								pos: position{line: 116, col: 66, offset: 2226},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 116, col: 66, offset: 2226},
										name: "Null",
									},
									&ruleRefExpr{
										pos:  position{line: 116, col: 73, offset: 2233},
										name: "Bool",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "InComparison",
			pos:  position{line: 125, col: 1, offset: 2391},
			expr: &actionExpr{
				pos: position{line: 125, col: 17, offset: 2407},
				run: (*parser).callonInComparison1,
				expr: &seqExpr{
					pos: position{line: 125, col: 17, offset: 2407},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 125, col: 17, offset: 2407},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 125, col: 23, offset: 2413},
								name: "Value",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 29, offset: 2419},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 125, col: 31, offset: 2421},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 125, col: 34, offset: 2424},
								name: "In",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 37, offset: 2427},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 125, col: 39, offset: 2429},
							label: "rest",
							expr: &ruleRefExpr{
								pos:  position{line: 125, col: 44, offset: 2434},
								name: "InList",
							},
						},
					},
				},
			},
		},
		{
			name: "IdentifierComparison",
			pos:  position{line: 139, col: 1, offset: 2695},
			expr: &actionExpr{
				pos: position{line: 139, col: 25, offset: 2719},
				run: (*parser).callonIdentifierComparison1,
				expr: &labeledExpr{
					pos:   position{line: 139, col: 25, offset: 2719},
					label: "i",
					expr: &ruleRefExpr{
						pos:  position{line: 139, col: 27, offset: 2721},
						name: "Identifier",
					},
				},
			},
		},
		{
			name: "InList",
			pos:  position{line: 152, col: 1, offset: 2861},
			expr: &choiceExpr{
				pos: position{line: 152, col: 11, offset: 2871},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 152, col: 11, offset: 2871},
						name: "EmptyInList",
					},
					&ruleRefExpr{
						pos:  position{line: 152, col: 25, offset: 2885},
						name: "NonEmptyInList",
					},
				},
			},
		},
		{
			name: "EmptyInList",
			pos:  position{line: 154, col: 1, offset: 2901},
			expr: &actionExpr{
				pos: position{line: 154, col: 16, offset: 2916},
				run: (*parser).callonEmptyInList1,
				expr: &seqExpr{
					pos: position{line: 154, col: 16, offset: 2916},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 154, col: 16, offset: 2916},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 154, col: 20, offset: 2920},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 154, col: 22, offset: 2922},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "NonEmptyInList",
			pos:  position{line: 158, col: 1, offset: 2961},
			expr: &actionExpr{
				pos: position{line: 158, col: 19, offset: 2979},
				run: (*parser).callonNonEmptyInList1,
				expr: &seqExpr{
					pos: position{line: 158, col: 19, offset: 2979},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 158, col: 19, offset: 2979},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 158, col: 23, offset: 2983},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 158, col: 25, offset: 2985},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 158, col: 31, offset: 2991},
								name: "UnbracketedValue",
							},
						},
						&labeledExpr{
							pos:   position{line: 158, col: 48, offset: 3008},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 158, col: 53, offset: 3013},
								expr: &seqExpr{
									pos: position{line: 158, col: 55, offset: 3015},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 158, col: 55, offset: 3015},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 158, col: 57, offset: 3017},
											val:        ",",
											ignoreCase: false,
											want:       "\",\"",
										},
										&ruleRefExpr{
											pos:  position{line: 158, col: 61, offset: 3021},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 158, col: 63, offset: 3023},
											name: "UnbracketedValue",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 158, col: 82, offset: 3042},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 158, col: 84, offset: 3044},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 168, col: 1, offset: 3120},
			expr: &choiceExpr{
				pos: position{line: 168, col: 10, offset: 3129},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 168, col: 10, offset: 3129},
						name: "BracketedValue",
					},
					&ruleRefExpr{
						pos:  position{line: 168, col: 27, offset: 3146},
						name: "UnbracketedValue",
					},
				},
			},
		},
		{
			name: "BracketedValue",
			pos:  position{line: 170, col: 1, offset: 3164},
			expr: &actionExpr{
				pos: position{line: 170, col: 19, offset: 3182},
				run: (*parser).callonBracketedValue1,
				expr: &seqExpr{
					pos: position{line: 170, col: 19, offset: 3182},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 170, col: 19, offset: 3182},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 170, col: 23, offset: 3186},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 170, col: 25, offset: 3188},
							label: "i",
							expr: &ruleRefExpr{
								pos:  position{line: 170, col: 27, offset: 3190},
								name: "Value",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 170, col: 33, offset: 3196},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 170, col: 35, offset: 3198},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "UnbracketedValue",
			pos:  position{line: 174, col: 1, offset: 3223},
			expr: &choiceExpr{
				pos: position{line: 174, col: 21, offset: 3243},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 174, col: 21, offset: 3243},
						name: "TimeCalculation",
					},
					&ruleRefExpr{
						pos:  position{line: 174, col: 39, offset: 3261},
						name: "Constant",
					},
					&ruleRefExpr{
						pos:  position{line: 174, col: 50, offset: 3272},
						name: "Jsonb",
					},
					&ruleRefExpr{
						pos:  position{line: 174, col: 58, offset: 3280},
						name: "Identifier",
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 181, col: 1, offset: 3315},
			expr: &choiceExpr{
				pos: position{line: 181, col: 15, offset: 3329},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 181, col: 15, offset: 3329},
						name: "Jsonb",
					},
					&ruleRefExpr{
						pos:  position{line: 181, col: 23, offset: 3337},
						name: "ColumnIdentifier",
					},
				},
			},
		},
		{
			name: "ColumnIdentifier",
			pos:  position{line: 183, col: 1, offset: 3355},
			expr: &choiceExpr{
				pos: position{line: 183, col: 21, offset: 3375},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 183, col: 21, offset: 3375},
						name: "QuotedIdentifier",
					},
					&ruleRefExpr{
						pos:  position{line: 183, col: 40, offset: 3394},
						name: "UnquotedIdentifier",
					},
				},
			},
		},
		{
			name: "QuotedIdentifier",
			pos:  position{line: 185, col: 1, offset: 3414},
			expr: &actionExpr{
				pos: position{line: 185, col: 21, offset: 3434},
				run: (*parser).callonQuotedIdentifier1,
				expr: &seqExpr{
					pos: position{line: 185, col: 21, offset: 3434},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 185, col: 21, offset: 3434},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 185, col: 25, offset: 3438},
							expr: &choiceExpr{
								pos: position{line: 185, col: 26, offset: 3439},
								alternatives: []interface{}{
									&litMatcher{
										pos:        position{line: 185, col: 26, offset: 3439},
										val:        "\"\"",
										ignoreCase: false,
										want:       "\"\\\"\\\"\"",
									},
									&charClassMatcher{
										pos:        position{line: 185, col: 33, offset: 3446},
										val:        "[^\"]",
										chars:      []rune{'"'},
										ignoreCase: false,
										inverted:   true,
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 185, col: 40, offset: 3453},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "UnquotedIdentifier",
			pos:  position{line: 196, col: 1, offset: 3649},
			expr: &actionExpr{
				pos: position{line: 196, col: 23, offset: 3671},
				run: (*parser).callonUnquotedIdentifier1,
				expr: &seqExpr{
					pos: position{line: 196, col: 23, offset: 3671},
					exprs: []interface{}{
						&charClassMatcher{
							pos:        position{line: 196, col: 23, offset: 3671},
							val:        "[A-Za-z_]",
							chars:      []rune{'_'},
							ranges:     []rune{'A', 'Z', 'a', 'z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 196, col: 32, offset: 3680},
							expr: &charClassMatcher{
								pos:        position{line: 196, col: 32, offset: 3680},
								val:        "[A-Za-z0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'A', 'Z', 'a', 'z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Jsonb",
			pos:  position{line: 206, col: 1, offset: 3843},
			expr: &actionExpr{
				pos: position{line: 206, col: 10, offset: 3852},
				run: (*parser).callonJsonb1,
				expr: &seqExpr{
					pos: position{line: 206, col: 10, offset: 3852},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 206, col: 10, offset: 3852},
							label: "i",
							expr: &ruleRefExpr{
								pos:  position{line: 206, col: 12, offset: 3854},
								name: "ColumnIdentifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 206, col: 29, offset: 3871},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 206, col: 31, offset: 3873},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 206, col: 34, offset: 3876},
								name: "JsonbOperator",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 206, col: 48, offset: 3890},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 206, col: 50, offset: 3892},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 206, col: 56, offset: 3898},
								name: "JsonbField",
							},
						},
						&labeledExpr{
							pos:   position{line: 206, col: 67, offset: 3909},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 206, col: 72, offset: 3914},
								expr: &seqExpr{
									pos: position{line: 206, col: 73, offset: 3915},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 206, col: 73, offset: 3915},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 206, col: 75, offset: 3917},
											name: "JsonbOperator",
										},
										&ruleRefExpr{
											pos:  position{line: 206, col: 89, offset: 3931},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 206, col: 91, offset: 3933},
											name: "JsonbField",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "JsonbField",
			pos:  position{line: 217, col: 1, offset: 4221},
			expr: &choiceExpr{
				pos: position{line: 217, col: 15, offset: 4235},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 217, col: 15, offset: 4235},
						name: "String",
					},
					&ruleRefExpr{
						pos:  position{line: 217, col: 24, offset: 4244},
						name: "Integer",
					},
				},
			},
		},
		{
			name: "JsonbOperator",
			pos:  position{line: 219, col: 1, offset: 4253},
			expr: &actionExpr{
				pos: position{line: 219, col: 18, offset: 4270},
				run: (*parser).callonJsonbOperator1,
				expr: &seqExpr{
					pos: position{line: 219, col: 18, offset: 4270},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 219, col: 18, offset: 4270},
							val:        "->",
							ignoreCase: false,
							want:       "\"->\"",
						},
						&zeroOrOneExpr{
							pos: position{line: 219, col: 23, offset: 4275},
							expr: &litMatcher{
								pos:        position{line: 219, col: 23, offset: 4275},
								val:        ">",
								ignoreCase: false,
								want:       "\">\"",
							},
						},
					},
				},
			},
		},
		{
			name: "CompareOperator",
			pos:  position{line: 235, col: 1, offset: 4473},
			expr: &actionExpr{
				pos: position{line: 235, col: 20, offset: 4492},
				run: (*parser).callonCompareOperator1,
				expr: &choiceExpr{
					pos: position{line: 235, col: 21, offset: 4493},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 235, col: 21, offset: 4493},
							val:        "<=",
							ignoreCase: false,
							want:       "\"<=\"",
						},
						&litMatcher{
							pos:        position{line: 235, col: 28, offset: 4500},
							val:        "<>",
							ignoreCase: false,
							want:       "\"<>\"",
						},
						&litMatcher{
							pos:        position{line: 235, col: 35, offset: 4507},
							val:        ">=",
							ignoreCase: false,
							want:       "\">=\"",
						},
						&litMatcher{
							pos:        position{line: 235, col: 42, offset: 4514},
							val:        "!=",
							ignoreCase: false,
							want:       "\"!=\"",
						},
						&litMatcher{
							pos:        position{line: 235, col: 49, offset: 4521},
							val:        "<",
							ignoreCase: false,
							want:       "\"<\"",
						},
						&litMatcher{
							pos:        position{line: 235, col: 55, offset: 4527},
							val:        "=",
							ignoreCase: false,
							want:       "\"=\"",
						},
						&litMatcher{
							pos:        position{line: 235, col: 61, offset: 4533},
							val:        ">",
							ignoreCase: false,
							want:       "\">\"",
						},
					},
				},
			},
		},
		{
			name: "And",
			pos:  position{line: 245, col: 1, offset: 4653},
			expr: &actionExpr{
				pos: position{line: 245, col: 8, offset: 4660},
				run: (*parser).callonAnd1,
				expr: &litMatcher{
					pos:        position{line: 245, col: 8, offset: 4660},
					val:        "and",
					ignoreCase: true,
					want:       "\"and\"i",
				},
			},
		},
		{
			name: "Or",
			pos:  position{line: 255, col: 1, offset: 4790},
			expr: &actionExpr{
				pos: position{line: 255, col: 7, offset: 4796},
				run: (*parser).callonOr1,
				expr: &litMatcher{
					pos:        position{line: 255, col: 7, offset: 4796},
					val:        "or",
					ignoreCase: true,
					want:       "\"or\"i",
				},
			},
		},
		{
			name: "Not",
			pos:  position{line: 265, col: 1, offset: 4924},
			expr: &actionExpr{
				pos: position{line: 265, col: 8, offset: 4931},
				run: (*parser).callonNot1,
				expr: &litMatcher{
					pos:        position{line: 265, col: 8, offset: 4931},
					val:        "not",
					ignoreCase: true,
					want:       "\"not\"i",
				},
			},
		},
		{
			name: "In",
			pos:  position{line: 275, col: 1, offset: 5061},
			expr: &actionExpr{
				pos: position{line: 275, col: 7, offset: 5067},
				run: (*parser).callonIn1,
				expr: &seqExpr{
					pos: position{line: 275, col: 7, offset: 5067},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 275, col: 7, offset: 5067},
							label: "not",
							expr: &zeroOrOneExpr{
								pos: position{line: 275, col: 11, offset: 5071},
								expr: &seqExpr{
									pos: position{line: 275, col: 12, offset: 5072},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 275, col: 12, offset: 5072},
											val:        "not",
											ignoreCase: true,
											want:       "\"not\"i",
										},
										&ruleRefExpr{
											pos:  position{line: 275, col: 19, offset: 5079},
											name: "_",
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 275, col: 23, offset: 5083},
							val:        "in",
							ignoreCase: true,
							want:       "\"in\"i",
						},
					},
				},
			},
		},
		{
			name: "Like",
			pos:  position{line: 288, col: 1, offset: 5256},
			expr: &actionExpr{
				pos: position{line: 288, col: 9, offset: 5264},
				run: (*parser).callonLike1,
				expr: &seqExpr{
					pos: position{line: 288, col: 9, offset: 5264},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 288, col: 9, offset: 5264},
							label: "not",
							expr: &zeroOrOneExpr{
								pos: position{line: 288, col: 13, offset: 5268},
								expr: &seqExpr{
									pos: position{line: 288, col: 14, offset: 5269},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 288, col: 14, offset: 5269},
											val:        "not",
											ignoreCase: true,
											want:       "\"not\"i",
										},
										&ruleRefExpr{
											pos:  position{line: 288, col: 21, offset: 5276},
											name: "_",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 288, col: 25, offset: 5280},
							label: "like",
							expr: &ruleRefExpr{
								pos:  position{line: 288, col: 30, offset: 5285},
								name: "LikeOrIlike",
							},
						},
					},
				},
			},
		},
		{
			name: "LikeOrIlike",
			pos:  position{line: 302, col: 1, offset: 5519},
			expr: &actionExpr{
				pos: position{line: 302, col: 16, offset: 5534},
				run: (*parser).callonLikeOrIlike1,
				expr: &choiceExpr{
					pos: position{line: 302, col: 17, offset: 5535},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 302, col: 17, offset: 5535},
							val:        "like",
							ignoreCase: true,
							want:       "\"like\"i",
						},
						&litMatcher{
							pos:        position{line: 302, col: 27, offset: 5545},
							val:        "ilike",
							ignoreCase: true,
							want:       "\"ilike\"i",
						},
					},
				},
			},
		},
		{
			name: "Is",
			pos:  position{line: 307, col: 1, offset: 5602},
			expr: &actionExpr{
				pos: position{line: 307, col: 7, offset: 5608},
				run: (*parser).callonIs1,
				expr: &seqExpr{
					pos: position{line: 307, col: 7, offset: 5608},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 307, col: 7, offset: 5608},
							val:        "is",
							ignoreCase: true,
							want:       "\"is\"i",
						},
						&labeledExpr{
							pos:   position{line: 307, col: 13, offset: 5614},
							label: "not",
							expr: &zeroOrOneExpr{
								pos: position{line: 307, col: 17, offset: 5618},
								expr: &seqExpr{
									pos: position{line: 307, col: 18, offset: 5619},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 307, col: 18, offset: 5619},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 307, col: 20, offset: 5621},
											val:        "not",
											ignoreCase: true,
											want:       "\"not\"i",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "TimeCalculation",
			pos:  position{line: 327, col: 1, offset: 5870},
			expr: &actionExpr{
				pos: position{line: 327, col: 20, offset: 5889},
				run: (*parser).callonTimeCalculation1,
				expr: &seqExpr{
					pos: position{line: 327, col: 20, offset: 5889},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 327, col: 20, offset: 5889},
							label: "now",
							expr: &ruleRefExpr{
								pos:  position{line: 327, col: 24, offset: 5893},
								name: "NoArgsFunction",
							},
						},
						&labeledExpr{
							pos:   position{line: 327, col: 39, offset: 5908},
							label: "interval",
							expr: &zeroOrOneExpr{
								pos: position{line: 327, col: 48, offset: 5917},
								expr: &seqExpr{
									pos: position{line: 327, col: 49, offset: 5918},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 327, col: 49, offset: 5918},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 327, col: 51, offset: 5920},
											name: "Add",
										},
										&ruleRefExpr{
											pos:  position{line: 327, col: 55, offset: 5924},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 327, col: 57, offset: 5926},
											name: "StringOperatorFunction",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Add",
			pos:  position{line: 342, col: 1, offset: 6334},
			expr: &actionExpr{
				pos: position{line: 342, col: 8, offset: 6341},
				run: (*parser).callonAdd1,
				expr: &choiceExpr{
					pos: position{line: 342, col: 9, offset: 6342},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 342, col: 9, offset: 6342},
							val:        "+",
							ignoreCase: false,
							want:       "\"+\"",
						},
						&litMatcher{
							pos:        position{line: 342, col: 15, offset: 6348},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
					},
				},
			},
		},
		{
			name: "Function",
			pos:  position{line: 352, col: 1, offset: 6468},
			expr: &choiceExpr{
				pos: position{line: 352, col: 13, offset: 6480},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 352, col: 13, offset: 6480},
						name: "StringOperatorFunction",
					},
					&ruleRefExpr{
						pos:  position{line: 352, col: 38, offset: 6505},
						name: "NoArgsFunction",
					},
				},
			},
		},
		{
			name: "NoArgsFunction",
			pos:  position{line: 354, col: 1, offset: 6521},
			expr: &actionExpr{
				pos: position{line: 354, col: 19, offset: 6539},
				run: (*parser).callonNoArgsFunction1,
				expr: &seqExpr{
					pos: position{line: 354, col: 19, offset: 6539},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 354, col: 19, offset: 6539},
							name: "NoArgsFunctionName",
						},
						&litMatcher{
							pos:        position{line: 354, col: 38, offset: 6558},
							val:        "()",
							ignoreCase: false,
							want:       "\"()\"",
						},
					},
				},
			},
		},
		{
			name: "NoArgsFunctionName",
			pos:  position{line: 369, col: 1, offset: 6828},
			expr: &litMatcher{
				pos:        position{line: 369, col: 23, offset: 6850},
				val:        "now",
				ignoreCase: true,
				want:       "\"now\"i",
			},
		},
		{
			name: "StringOperatorFunction",
			pos:  position{line: 371, col: 1, offset: 6858},
			expr: &actionExpr{
				pos: position{line: 371, col: 27, offset: 6884},
				run: (*parser).callonStringOperatorFunction1,
				expr: &seqExpr{
					pos: position{line: 371, col: 27, offset: 6884},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 371, col: 27, offset: 6884},
							label: "fn",
							expr: &ruleRefExpr{
								pos:  position{line: 371, col: 30, offset: 6887},
								name: "StringOperatorFunctionName",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 371, col: 57, offset: 6914},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 371, col: 59, offset: 6916},
							label: "s",
							expr: &ruleRefExpr{
								pos:  position{line: 371, col: 61, offset: 6918},
								name: "String",
							},
						},
					},
				},
			},
		},
		{
			name: "StringOperatorFunctionName",
			pos:  position{line: 386, col: 1, offset: 7202},
			expr: &litMatcher{
				pos:        position{line: 386, col: 31, offset: 7232},
				val:        "interval",
				ignoreCase: true,
				want:       "\"interval\"i",
			},
		},
		{
			name: "Constant",
			pos:  position{line: 393, col: 1, offset: 7266},
			expr: &choiceExpr{
				pos: position{line: 393, col: 13, offset: 7278},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 393, col: 13, offset: 7278},
						name: "Bool",
					},
					&ruleRefExpr{
						pos:  position{line: 393, col: 20, offset: 7285},
						name: "Number",
					},
					&ruleRefExpr{
						pos:  position{line: 393, col: 29, offset: 7294},
						name: "String",
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 395, col: 1, offset: 7302},
			expr: &actionExpr{
				pos: position{line: 395, col: 11, offset: 7312},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 395, col: 11, offset: 7312},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 395, col: 11, offset: 7312},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 395, col: 15, offset: 7316},
							expr: &choiceExpr{
								pos: position{line: 395, col: 16, offset: 7317},
								alternatives: []interface{}{
									&litMatcher{
										pos:        position{line: 395, col: 16, offset: 7317},
										val:        "''",
										ignoreCase: false,
										want:       "\"''\"",
									},
									&charClassMatcher{
										pos:        position{line: 395, col: 23, offset: 7324},
										val:        "[^']",
										chars:      []rune{'\''},
										ignoreCase: false,
										inverted:   true,
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 395, col: 30, offset: 7331},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 406, col: 1, offset: 7516},
			expr: &actionExpr{
				pos: position{line: 406, col: 11, offset: 7526},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 406, col: 11, offset: 7526},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 406, col: 11, offset: 7526},
							expr: &litMatcher{
								pos:        position{line: 406, col: 11, offset: 7526},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 406, col: 16, offset: 7531},
							name: "Integer",
						},
						&zeroOrOneExpr{
							pos: position{line: 406, col: 24, offset: 7539},
							expr: &seqExpr{
								pos: position{line: 406, col: 26, offset: 7541},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 406, col: 26, offset: 7541},
										val:        ".",
										ignoreCase: false,
										want:       "\".\"",
									},
									&oneOrMoreExpr{
										pos: position{line: 406, col: 30, offset: 7545},
										expr: &ruleRefExpr{
											pos:  position{line: 406, col: 30, offset: 7545},
											name: "DecimalDigit",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 406, col: 47, offset: 7562},
							expr: &ruleRefExpr{
								pos:  position{line: 406, col: 47, offset: 7562},
								name: "Exponent",
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 418, col: 1, offset: 7777},
			expr: &actionExpr{
				pos: position{line: 418, col: 12, offset: 7788},
				run: (*parser).callonInteger1,
				expr: &choiceExpr{
					pos: position{line: 418, col: 13, offset: 7789},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 418, col: 13, offset: 7789},
							val:        "0",
							ignoreCase: false,
							want:       "\"0\"",
						},
						&seqExpr{
							pos: position{line: 418, col: 19, offset: 7795},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 418, col: 19, offset: 7795},
									name: "NonZeroDecimalDigit",
								},
								&zeroOrMoreExpr{
									pos: position{line: 418, col: 39, offset: 7815},
									expr: &ruleRefExpr{
										pos:  position{line: 418, col: 39, offset: 7815},
										name: "DecimalDigit",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Exponent",
			pos:  position{line: 428, col: 1, offset: 7949},
			expr: &seqExpr{
				pos: position{line: 428, col: 13, offset: 7961},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 428, col: 13, offset: 7961},
						val:        "e",
						ignoreCase: true,
						want:       "\"e\"i",
					},
					&zeroOrOneExpr{
						pos: position{line: 428, col: 18, offset: 7966},
						expr: &charClassMatcher{
							pos:        position{line: 428, col: 18, offset: 7966},
							val:        "[+-]",
							chars:      []rune{'+', '-'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&oneOrMoreExpr{
						pos: position{line: 428, col: 24, offset: 7972},
						expr: &ruleRefExpr{
							pos:  position{line: 428, col: 24, offset: 7972},
							name: "DecimalDigit",
						},
					},
				},
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 430, col: 1, offset: 7987},
			expr: &charClassMatcher{
				pos:        position{line: 430, col: 17, offset: 8003},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "NonZeroDecimalDigit",
			pos:  position{line: 432, col: 1, offset: 8010},
			expr: &charClassMatcher{
				pos:        position{line: 432, col: 24, offset: 8033},
				val:        "[1-9]",
				ranges:     []rune{'1', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Bool",
			pos:  position{line: 434, col: 1, offset: 8040},
			expr: &actionExpr{
				pos: position{line: 434, col: 9, offset: 8048},
				run: (*parser).callonBool1,
				expr: &choiceExpr{
					pos: position{line: 434, col: 10, offset: 8049},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 434, col: 10, offset: 8049},
							val:        "true",
							ignoreCase: true,
							want:       "\"true\"i",
						},
						&litMatcher{
							pos:        position{line: 434, col: 20, offset: 8059},
							val:        "false",
							ignoreCase: true,
							want:       "\"false\"i",
						},
					},
				},
			},
		},
		{
			name: "Null",
			pos:  position{line: 444, col: 1, offset: 8203},
			expr: &actionExpr{
				pos: position{line: 444, col: 9, offset: 8211},
				run: (*parser).callonNull1,
				expr: &litMatcher{
					pos:        position{line: 444, col: 9, offset: 8211},
					val:        "null",
					ignoreCase: true,
					want:       "\"null\"i",
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 460, col: 1, offset: 8385},
			expr: &actionExpr{
				pos: position{line: 460, col: 6, offset: 8390},
				run: (*parser).callon_1,
				expr: &zeroOrMoreExpr{
					pos: position{line: 460, col: 6, offset: 8390},
					expr: &charClassMatcher{
						pos:        position{line: 460, col: 6, offset: 8390},
						val:        "[ \\n\\t\\r]",
						chars:      []rune{' ', '\n', '\t', '\r'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 470, col: 1, offset: 8544},
			expr: &actionExpr{
				pos: position{line: 470, col: 8, offset: 8551},
				run: (*parser).callonEOF1,
				expr: &notExpr{
					pos: position{line: 470, col: 8, offset: 8551},
					expr: &anyMatcher{
						line: 470, col: 9, offset: 8552,
					},
				},
			},
		},
	},
}

func (c *current) onInput1(i interface{}) (interface{}, error) {
	return i, nil
}

func (p *parser) callonInput1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1(stack["i"])
}

func (c *current) onOrComparison1(first, rest interface{}) (interface{}, error) {
	exprs := eval(first, rest)
	if len(exprs) <= 1 {
		return first, nil
	}
	n := ComparisonNode{
		Type:   "or",
		Values: exprs,
	}
	return n, nil
}

func (p *parser) callonOrComparison1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrComparison1(stack["first"], stack["rest"])
}

func (c *current) onAndComparison1(first, rest interface{}) (interface{}, error) {
	exprs := eval(first, rest)
	if len(exprs) <= 1 {
		return first, nil
	}
	n := ComparisonNode{
		Type:   "and",
		Values: exprs,
	}
	return n, nil
}

func (p *parser) callonAndComparison1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndComparison1(stack["first"], stack["rest"])
}

func (c *current) onMultiComparison1(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonMultiComparison1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiComparison1(stack["expr"])
}

func (c *current) onNotComparison1(op, right interface{}) (interface{}, error) {
	n := ComparisonNode{
		Type:     "not",
		Operator: op.(CodeNode),
		Values:   []ComparisonNode{right.(ComparisonNode)},
	}
	return n, nil
}

func (p *parser) callonNotComparison1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNotComparison1(stack["op"], stack["right"])
}

func (c *current) onLeftRightComparison1(left, op, right interface{}) (interface{}, error) {
	n := ComparisonNode{
		Type:     "compare",
		Operator: op.(CodeNode),
		Values:   []CodeNode{left.(CodeNode), right.(CodeNode)},
	}
	return n, nil
}

func (p *parser) callonLeftRightComparison1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLeftRightComparison1(stack["left"], stack["op"], stack["right"])
}

func (c *current) onLikeComparison1(left, op, right interface{}) (interface{}, error) {
	n := ComparisonNode{
		Type:     "like",
		Operator: op.(CodeNode),
		Values:   []CodeNode{left.(CodeNode), right.(CodeNode)},
	}
	return n, nil
}

func (p *parser) callonLikeComparison1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLikeComparison1(stack["left"], stack["op"], stack["right"])
}

func (c *current) onIsComparison1(left, op, right interface{}) (interface{}, error) {
	n := ComparisonNode{
		Type:     "is",
		Operator: op.(CodeNode),
		Values:   []CodeNode{left.(CodeNode), right.(CodeNode)},
	}
	return n, nil
}

func (p *parser) callonIsComparison1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIsComparison1(stack["left"], stack["op"], stack["right"])
}

func (c *current) onInComparison1(first, op, rest interface{}) (interface{}, error) {
	exprs := []CodeNode{first.(CodeNode)}
	resti := toIfaceSlice(rest)
	for _, v := range resti {
		exprs = append(exprs, v.(CodeNode))
	}
	n := ComparisonNode{
		Type:     "in",
		Operator: op.(CodeNode),
		Values:   exprs,
	}
	return n, nil
}

func (p *parser) callonInComparison1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInComparison1(stack["first"], stack["op"], stack["rest"])
}

func (c *current) onIdentifierComparison1(i interface{}) (interface{}, error) {
	n := ComparisonNode{
		Type:   "identifier",
		Values: []CodeNode{i.(CodeNode)},
	}
	return n, nil
}

func (p *parser) callonIdentifierComparison1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifierComparison1(stack["i"])
}

func (c *current) onEmptyInList1() (interface{}, error) {
	return []interface{}{}, nil
}

func (p *parser) callonEmptyInList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEmptyInList1()
}

func (c *current) onNonEmptyInList1(first, rest interface{}) (interface{}, error) {
	exprs := eval(first, rest)
	return exprs, nil
}

func (p *parser) callonNonEmptyInList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNonEmptyInList1(stack["first"], stack["rest"])
}

func (c *current) onBracketedValue1(i interface{}) (interface{}, error) {
	return i, nil
}

func (p *parser) callonBracketedValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBracketedValue1(stack["i"])
}

func (c *current) onQuotedIdentifier1() (interface{}, error) {
	src := string(c.text)
	value := strings.ReplaceAll(src[1:len(src)-1], `""`, `"`)
	n := CodeNode{
		Type:   "quoted_identifier",
		Source: src,
		Value:  value,
	}
	return n, nil
}

func (p *parser) callonQuotedIdentifier1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onQuotedIdentifier1()
}

func (c *current) onUnquotedIdentifier1() (interface{}, error) {
	src := string(c.text)
	n := CodeNode{
		Type:   "unquoted_identifier",
		Source: src,
		Value:  strings.ToLower(src),
	}
	return n, nil
}

func (p *parser) callonUnquotedIdentifier1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnquotedIdentifier1()
}

func (c *current) onJsonb1(i, op, first, rest interface{}) (interface{}, error) {
	n := i.(CodeNode)
	n.JsonbSelector = []CodeNode{op.(CodeNode), first.(CodeNode)}
	resti := toIfaceSlice(rest)
	for _, e := range resti {
		ei := toIfaceSlice(e)
		n.JsonbSelector = append(n.JsonbSelector, ei[1].(CodeNode), ei[3].(CodeNode))
	}
	return n, nil
}

func (p *parser) callonJsonb1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onJsonb1(stack["i"], stack["op"], stack["first"], stack["rest"])
}

func (c *current) onJsonbOperator1() (interface{}, error) {
	s := string(c.text)
	n := CodeNode{
		Type:   "operator",
		Source: s,
		Value:  s,
	}
	return n, nil
}

func (p *parser) callonJsonbOperator1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onJsonbOperator1()
}

func (c *current) onCompareOperator1() (interface{}, error) {
	s := string(c.text)
	n := CodeNode{
		Type:   "operator",
		Source: s,
		Value:  s,
	}
	return n, nil
}

func (p *parser) callonCompareOperator1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCompareOperator1()
}

func (c *current) onAnd1() (interface{}, error) {
	src := string(c.text)
	n := CodeNode{
		Type:   "operator",
		Source: src,
		Value:  "and",
	}
	return n, nil
}

func (p *parser) callonAnd1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAnd1()
}

func (c *current) onOr1() (interface{}, error) {
	src := string(c.text)
	n := CodeNode{
		Type:   "operator",
		Source: src,
		Value:  "or",
	}
	return n, nil
}

func (p *parser) callonOr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOr1()
}

func (c *current) onNot1() (interface{}, error) {
	src := string(c.text)
	n := CodeNode{
		Type:   "operator",
		Source: src,
		Value:  "not",
	}
	return n, nil
}

func (p *parser) callonNot1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNot1()
}

func (c *current) onIn1(not interface{}) (interface{}, error) {
	src := string(c.text)
	n := CodeNode{
		Type:   "operator",
		Source: src,
		Value:  "in",
	}
	if not != nil {
		n.Value = "not in"
	}
	return n, nil
}

func (p *parser) callonIn1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIn1(stack["not"])
}

func (c *current) onLike1(not, like interface{}) (interface{}, error) {
	src := string(c.text)
	likeStr := strings.ToLower(like.(string))
	n := CodeNode{
		Type:   "operator",
		Source: src,
		Value:  likeStr,
	}
	if not != nil {
		n.Value = "not " + likeStr
	}
	return n, nil
}

func (p *parser) callonLike1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLike1(stack["not"], stack["like"])
}

func (c *current) onLikeOrIlike1() (interface{}, error) {
	src := string(c.text)
	return src, nil
}

func (p *parser) callonLikeOrIlike1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLikeOrIlike1()
}

func (c *current) onIs1(not interface{}) (interface{}, error) {
	src := string(c.text)
	n := CodeNode{
		Type:   "operator",
		Source: src,
		Value:  "is",
	}
	if not != nil {
		n.Value = "is not"
	}
	return n, nil
}

func (p *parser) callonIs1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIs1(stack["not"])
}

func (c *current) onTimeCalculation1(now, interval interface{}) (interface{}, error) {
	n := CodeNode{
		Type:   "time_calculation",
		Source: string(c.text),
		Value:  "now()",
	}
	if interval != nil {
		intervalSlice := toIfaceSlice(interval)
		addOp := intervalSlice[1].(CodeNode).Value
		intervalString, _ := CodeToSQL(intervalSlice[3].(FunctionNode).Args[0])
		n.Value += fmt.Sprintf(" %s interval %s", addOp, intervalString)
	}
	return n, nil
}

func (p *parser) callonTimeCalculation1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTimeCalculation1(stack["now"], stack["interval"])
}

func (c *current) onAdd1() (interface{}, error) {
	s := string(c.text)
	n := CodeNode{
		Type:   "operator",
		Source: s,
		Value:  s,
	}
	return n, nil
}

func (p *parser) callonAdd1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAdd1()
}

func (c *current) onNoArgsFunction1() (interface{}, error) {
	src := string(c.text)
	fnName := src[:len(src)-2]
	n := FunctionNode{
		Name: "function",
		Function: CodeNode{
			Type:   "function_name",
			Source: fnName,
			Value:  strings.ToLower(fnName),
		},
		Args: []CodeNode{},
	}
	return n, nil
}

func (p *parser) callonNoArgsFunction1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNoArgsFunction1()
}

func (c *current) onStringOperatorFunction1(fn, s interface{}) (interface{}, error) {
	src := string(c.text)
	fnName := src[:len(src)-2]
	n := FunctionNode{
		Name: "function",
		Function: CodeNode{
			Type:   "function_name",
			Source: fnName,
			Value:  strings.ToLower(fnName),
		},
		Args: []CodeNode{s.(CodeNode)},
	}
	return n, nil
}

func (p *parser) callonStringOperatorFunction1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringOperatorFunction1(stack["fn"], stack["s"])
}

func (c *current) onString1() (interface{}, error) {
	src := string(c.text)
	value := strings.ReplaceAll(src[1:len(src)-1], "''", "'")
	n := CodeNode{
		Type:   "string",
		Source: src,
		Value:  value,
	}
	return n, nil
}

func (p *parser) callonString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1()
}

func (c *current) onNumber1() (interface{}, error) {
	// JSON numbers have the same syntax as Go's, and are parseable using
	// strconv.
	src := string(c.text)
	n := CodeNode{
		Type:   "number",
		Source: src,
		Value:  src,
	}
	return n, nil
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onInteger1() (interface{}, error) {
	src := string(c.text)
	n := CodeNode{
		Type:   "number",
		Source: src,
		Value:  src,
	}
	return n, nil
}

func (p *parser) callonInteger1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

func (c *current) onBool1() (interface{}, error) {
	src := string(c.text)
	n := CodeNode{
		Type:   "bool",
		Source: src,
		Value:  strings.ToLower(src),
	}
	return n, nil
}

func (p *parser) callonBool1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool1()
}

func (c *current) onNull1() (interface{}, error) {
	src := string(c.text)
	n := CodeNode{
		Type:   "null",
		Source: src,
		Value:  strings.ToLower(src),
	}
	return n, nil
}

func (p *parser) callonNull1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNull1()
}

func (c *current) on_1() (interface{}, error) {
	src := string(c.text)
	n := CodeNode{
		Type:   "whitespace",
		Source: src,
	}
	if len(src) > 0 {
		n.Value = " "
	}
	return n, nil
}

func (p *parser) callon_1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.on_1()
}

func (c *current) onEOF1() (interface{}, error) {
	n := CodeNode{
		Type:   "eof",
		Source: "",
		Value:  "",
	}
	return n, nil
}

func (p *parser) callonEOF1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEOF1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}