version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - durationcheck
    - errcheck
    - forbidigo
    - gocheckcompilerdirectives
    - gocritic
    - gosec
    - govet
    - ineffassign
    - makezero
    - nilerr
    - nolintlint
    - reassign
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
        - singleCaseSwitch
        - assignOp
        - commentFormatting
    nolintlint:
      require-explanation: true
      require-specific: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
