/*
Package proto contains [protobuf] definitions and auto generated code for the plugin service interface.

It also contains extension methods for various autogenerated protobuf types.

[proto]: https://github.com/protocolbuffers/protobuf-go
*/
package proto
