// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.2
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WrapperPlugin_EstablishMessageStream_FullMethodName    = "/proto.WrapperPlugin/EstablishMessageStream"
	WrapperPlugin_GetSchema_FullMethodName                 = "/proto.WrapperPlugin/GetSchema"
	WrapperPlugin_Execute_FullMethodName                   = "/proto.WrapperPlugin/Execute"
	WrapperPlugin_SetConnectionConfig_FullMethodName       = "/proto.WrapperPlugin/SetConnectionConfig"
	WrapperPlugin_SetAllConnectionConfigs_FullMethodName   = "/proto.WrapperPlugin/SetAllConnectionConfigs"
	WrapperPlugin_UpdateConnectionConfigs_FullMethodName   = "/proto.WrapperPlugin/UpdateConnectionConfigs"
	WrapperPlugin_GetSupportedOperations_FullMethodName    = "/proto.WrapperPlugin/GetSupportedOperations"
	WrapperPlugin_SetCacheOptions_FullMethodName           = "/proto.WrapperPlugin/SetCacheOptions"
	WrapperPlugin_SetRateLimiters_FullMethodName           = "/proto.WrapperPlugin/SetRateLimiters"
	WrapperPlugin_GetRateLimiters_FullMethodName           = "/proto.WrapperPlugin/GetRateLimiters"
	WrapperPlugin_SetConnectionCacheOptions_FullMethodName = "/proto.WrapperPlugin/SetConnectionCacheOptions"
)

// WrapperPluginClient is the client API for WrapperPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WrapperPluginClient interface {
	EstablishMessageStream(ctx context.Context, in *EstablishMessageStreamRequest, opts ...grpc.CallOption) (WrapperPlugin_EstablishMessageStreamClient, error)
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (WrapperPlugin_ExecuteClient, error)
	SetConnectionConfig(ctx context.Context, in *SetConnectionConfigRequest, opts ...grpc.CallOption) (*SetConnectionConfigResponse, error)
	SetAllConnectionConfigs(ctx context.Context, in *SetAllConnectionConfigsRequest, opts ...grpc.CallOption) (*SetConnectionConfigResponse, error)
	UpdateConnectionConfigs(ctx context.Context, in *UpdateConnectionConfigsRequest, opts ...grpc.CallOption) (*UpdateConnectionConfigsResponse, error)
	GetSupportedOperations(ctx context.Context, in *GetSupportedOperationsRequest, opts ...grpc.CallOption) (*GetSupportedOperationsResponse, error)
	SetCacheOptions(ctx context.Context, in *SetCacheOptionsRequest, opts ...grpc.CallOption) (*SetCacheOptionsResponse, error)
	SetRateLimiters(ctx context.Context, in *SetRateLimitersRequest, opts ...grpc.CallOption) (*SetRateLimitersResponse, error)
	GetRateLimiters(ctx context.Context, in *GetRateLimitersRequest, opts ...grpc.CallOption) (*GetRateLimitersResponse, error)
	SetConnectionCacheOptions(ctx context.Context, in *SetConnectionCacheOptionsRequest, opts ...grpc.CallOption) (*SetConnectionCacheOptionsResponse, error)
}

type wrapperPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewWrapperPluginClient(cc grpc.ClientConnInterface) WrapperPluginClient {
	return &wrapperPluginClient{cc}
}

func (c *wrapperPluginClient) EstablishMessageStream(ctx context.Context, in *EstablishMessageStreamRequest, opts ...grpc.CallOption) (WrapperPlugin_EstablishMessageStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &WrapperPlugin_ServiceDesc.Streams[0], WrapperPlugin_EstablishMessageStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &wrapperPluginEstablishMessageStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WrapperPlugin_EstablishMessageStreamClient interface {
	Recv() (*PluginMessage, error)
	grpc.ClientStream
}

type wrapperPluginEstablishMessageStreamClient struct {
	grpc.ClientStream
}

func (x *wrapperPluginEstablishMessageStreamClient) Recv() (*PluginMessage, error) {
	m := new(PluginMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *wrapperPluginClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, WrapperPlugin_GetSchema_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrapperPluginClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (WrapperPlugin_ExecuteClient, error) {
	stream, err := c.cc.NewStream(ctx, &WrapperPlugin_ServiceDesc.Streams[1], WrapperPlugin_Execute_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &wrapperPluginExecuteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WrapperPlugin_ExecuteClient interface {
	Recv() (*ExecuteResponse, error)
	grpc.ClientStream
}

type wrapperPluginExecuteClient struct {
	grpc.ClientStream
}

func (x *wrapperPluginExecuteClient) Recv() (*ExecuteResponse, error) {
	m := new(ExecuteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *wrapperPluginClient) SetConnectionConfig(ctx context.Context, in *SetConnectionConfigRequest, opts ...grpc.CallOption) (*SetConnectionConfigResponse, error) {
	out := new(SetConnectionConfigResponse)
	err := c.cc.Invoke(ctx, WrapperPlugin_SetConnectionConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrapperPluginClient) SetAllConnectionConfigs(ctx context.Context, in *SetAllConnectionConfigsRequest, opts ...grpc.CallOption) (*SetConnectionConfigResponse, error) {
	out := new(SetConnectionConfigResponse)
	err := c.cc.Invoke(ctx, WrapperPlugin_SetAllConnectionConfigs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrapperPluginClient) UpdateConnectionConfigs(ctx context.Context, in *UpdateConnectionConfigsRequest, opts ...grpc.CallOption) (*UpdateConnectionConfigsResponse, error) {
	out := new(UpdateConnectionConfigsResponse)
	err := c.cc.Invoke(ctx, WrapperPlugin_UpdateConnectionConfigs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrapperPluginClient) GetSupportedOperations(ctx context.Context, in *GetSupportedOperationsRequest, opts ...grpc.CallOption) (*GetSupportedOperationsResponse, error) {
	out := new(GetSupportedOperationsResponse)
	err := c.cc.Invoke(ctx, WrapperPlugin_GetSupportedOperations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrapperPluginClient) SetCacheOptions(ctx context.Context, in *SetCacheOptionsRequest, opts ...grpc.CallOption) (*SetCacheOptionsResponse, error) {
	out := new(SetCacheOptionsResponse)
	err := c.cc.Invoke(ctx, WrapperPlugin_SetCacheOptions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrapperPluginClient) SetRateLimiters(ctx context.Context, in *SetRateLimitersRequest, opts ...grpc.CallOption) (*SetRateLimitersResponse, error) {
	out := new(SetRateLimitersResponse)
	err := c.cc.Invoke(ctx, WrapperPlugin_SetRateLimiters_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrapperPluginClient) GetRateLimiters(ctx context.Context, in *GetRateLimitersRequest, opts ...grpc.CallOption) (*GetRateLimitersResponse, error) {
	out := new(GetRateLimitersResponse)
	err := c.cc.Invoke(ctx, WrapperPlugin_GetRateLimiters_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrapperPluginClient) SetConnectionCacheOptions(ctx context.Context, in *SetConnectionCacheOptionsRequest, opts ...grpc.CallOption) (*SetConnectionCacheOptionsResponse, error) {
	out := new(SetConnectionCacheOptionsResponse)
	err := c.cc.Invoke(ctx, WrapperPlugin_SetConnectionCacheOptions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WrapperPluginServer is the server API for WrapperPlugin service.
// All implementations must embed UnimplementedWrapperPluginServer
// for forward compatibility
type WrapperPluginServer interface {
	EstablishMessageStream(*EstablishMessageStreamRequest, WrapperPlugin_EstablishMessageStreamServer) error
	GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)
	Execute(*ExecuteRequest, WrapperPlugin_ExecuteServer) error
	SetConnectionConfig(context.Context, *SetConnectionConfigRequest) (*SetConnectionConfigResponse, error)
	SetAllConnectionConfigs(context.Context, *SetAllConnectionConfigsRequest) (*SetConnectionConfigResponse, error)
	UpdateConnectionConfigs(context.Context, *UpdateConnectionConfigsRequest) (*UpdateConnectionConfigsResponse, error)
	GetSupportedOperations(context.Context, *GetSupportedOperationsRequest) (*GetSupportedOperationsResponse, error)
	SetCacheOptions(context.Context, *SetCacheOptionsRequest) (*SetCacheOptionsResponse, error)
	SetRateLimiters(context.Context, *SetRateLimitersRequest) (*SetRateLimitersResponse, error)
	GetRateLimiters(context.Context, *GetRateLimitersRequest) (*GetRateLimitersResponse, error)
	SetConnectionCacheOptions(context.Context, *SetConnectionCacheOptionsRequest) (*SetConnectionCacheOptionsResponse, error)
	mustEmbedUnimplementedWrapperPluginServer()
}

// UnimplementedWrapperPluginServer must be embedded to have forward compatible implementations.
type UnimplementedWrapperPluginServer struct {
}

func (UnimplementedWrapperPluginServer) EstablishMessageStream(*EstablishMessageStreamRequest, WrapperPlugin_EstablishMessageStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method EstablishMessageStream not implemented")
}
func (UnimplementedWrapperPluginServer) GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedWrapperPluginServer) Execute(*ExecuteRequest, WrapperPlugin_ExecuteServer) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedWrapperPluginServer) SetConnectionConfig(context.Context, *SetConnectionConfigRequest) (*SetConnectionConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConnectionConfig not implemented")
}
func (UnimplementedWrapperPluginServer) SetAllConnectionConfigs(context.Context, *SetAllConnectionConfigsRequest) (*SetConnectionConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAllConnectionConfigs not implemented")
}
func (UnimplementedWrapperPluginServer) UpdateConnectionConfigs(context.Context, *UpdateConnectionConfigsRequest) (*UpdateConnectionConfigsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConnectionConfigs not implemented")
}
func (UnimplementedWrapperPluginServer) GetSupportedOperations(context.Context, *GetSupportedOperationsRequest) (*GetSupportedOperationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupportedOperations not implemented")
}
func (UnimplementedWrapperPluginServer) SetCacheOptions(context.Context, *SetCacheOptionsRequest) (*SetCacheOptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCacheOptions not implemented")
}
func (UnimplementedWrapperPluginServer) SetRateLimiters(context.Context, *SetRateLimitersRequest) (*SetRateLimitersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRateLimiters not implemented")
}
func (UnimplementedWrapperPluginServer) GetRateLimiters(context.Context, *GetRateLimitersRequest) (*GetRateLimitersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRateLimiters not implemented")
}
func (UnimplementedWrapperPluginServer) SetConnectionCacheOptions(context.Context, *SetConnectionCacheOptionsRequest) (*SetConnectionCacheOptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConnectionCacheOptions not implemented")
}
func (UnimplementedWrapperPluginServer) mustEmbedUnimplementedWrapperPluginServer() {}

// UnsafeWrapperPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WrapperPluginServer will
// result in compilation errors.
type UnsafeWrapperPluginServer interface {
	mustEmbedUnimplementedWrapperPluginServer()
}

func RegisterWrapperPluginServer(s grpc.ServiceRegistrar, srv WrapperPluginServer) {
	s.RegisterService(&WrapperPlugin_ServiceDesc, srv)
}

func _WrapperPlugin_EstablishMessageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EstablishMessageStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WrapperPluginServer).EstablishMessageStream(m, &wrapperPluginEstablishMessageStreamServer{stream})
}

type WrapperPlugin_EstablishMessageStreamServer interface {
	Send(*PluginMessage) error
	grpc.ServerStream
}

type wrapperPluginEstablishMessageStreamServer struct {
	grpc.ServerStream
}

func (x *wrapperPluginEstablishMessageStreamServer) Send(m *PluginMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _WrapperPlugin_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WrapperPluginServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WrapperPlugin_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WrapperPluginServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WrapperPlugin_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WrapperPluginServer).Execute(m, &wrapperPluginExecuteServer{stream})
}

type WrapperPlugin_ExecuteServer interface {
	Send(*ExecuteResponse) error
	grpc.ServerStream
}

type wrapperPluginExecuteServer struct {
	grpc.ServerStream
}

func (x *wrapperPluginExecuteServer) Send(m *ExecuteResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _WrapperPlugin_SetConnectionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConnectionConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WrapperPluginServer).SetConnectionConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WrapperPlugin_SetConnectionConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WrapperPluginServer).SetConnectionConfig(ctx, req.(*SetConnectionConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WrapperPlugin_SetAllConnectionConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAllConnectionConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WrapperPluginServer).SetAllConnectionConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WrapperPlugin_SetAllConnectionConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WrapperPluginServer).SetAllConnectionConfigs(ctx, req.(*SetAllConnectionConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WrapperPlugin_UpdateConnectionConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConnectionConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WrapperPluginServer).UpdateConnectionConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WrapperPlugin_UpdateConnectionConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WrapperPluginServer).UpdateConnectionConfigs(ctx, req.(*UpdateConnectionConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WrapperPlugin_GetSupportedOperations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupportedOperationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WrapperPluginServer).GetSupportedOperations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WrapperPlugin_GetSupportedOperations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WrapperPluginServer).GetSupportedOperations(ctx, req.(*GetSupportedOperationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WrapperPlugin_SetCacheOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCacheOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WrapperPluginServer).SetCacheOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WrapperPlugin_SetCacheOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WrapperPluginServer).SetCacheOptions(ctx, req.(*SetCacheOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WrapperPlugin_SetRateLimiters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRateLimitersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WrapperPluginServer).SetRateLimiters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WrapperPlugin_SetRateLimiters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WrapperPluginServer).SetRateLimiters(ctx, req.(*SetRateLimitersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WrapperPlugin_GetRateLimiters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRateLimitersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WrapperPluginServer).GetRateLimiters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WrapperPlugin_GetRateLimiters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WrapperPluginServer).GetRateLimiters(ctx, req.(*GetRateLimitersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WrapperPlugin_SetConnectionCacheOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConnectionCacheOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WrapperPluginServer).SetConnectionCacheOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WrapperPlugin_SetConnectionCacheOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WrapperPluginServer).SetConnectionCacheOptions(ctx, req.(*SetConnectionCacheOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WrapperPlugin_ServiceDesc is the grpc.ServiceDesc for WrapperPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WrapperPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WrapperPlugin",
	HandlerType: (*WrapperPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSchema",
			Handler:    _WrapperPlugin_GetSchema_Handler,
		},
		{
			MethodName: "SetConnectionConfig",
			Handler:    _WrapperPlugin_SetConnectionConfig_Handler,
		},
		{
			MethodName: "SetAllConnectionConfigs",
			Handler:    _WrapperPlugin_SetAllConnectionConfigs_Handler,
		},
		{
			MethodName: "UpdateConnectionConfigs",
			Handler:    _WrapperPlugin_UpdateConnectionConfigs_Handler,
		},
		{
			MethodName: "GetSupportedOperations",
			Handler:    _WrapperPlugin_GetSupportedOperations_Handler,
		},
		{
			MethodName: "SetCacheOptions",
			Handler:    _WrapperPlugin_SetCacheOptions_Handler,
		},
		{
			MethodName: "SetRateLimiters",
			Handler:    _WrapperPlugin_SetRateLimiters_Handler,
		},
		{
			MethodName: "GetRateLimiters",
			Handler:    _WrapperPlugin_GetRateLimiters_Handler,
		},
		{
			MethodName: "SetConnectionCacheOptions",
			Handler:    _WrapperPlugin_SetConnectionCacheOptions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EstablishMessageStream",
			Handler:       _WrapperPlugin_EstablishMessageStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Execute",
			Handler:       _WrapperPlugin_Execute_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}
